# Generated by Django 5.2.15 on 2026-06-18 06:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('icon', models.CharField(default='✦', max_length=32, verbose_name='Іконка')),
                ('color', models.CharField(default='#f97316', max_length=32, verbose_name='Колір')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Назва')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Категорія')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=160, verbose_name='ПІБ')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('volunteer', 'Волонтер'), ('coordinator', 'Координатор'), ('organization_manager', 'Менеджер організації'), ('admin', 'Адміністратор')], default='volunteer', max_length=32, verbose_name='Роль')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний')], default='active', max_length=16, verbose_name='Статус')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('bio', models.TextField(blank=True, verbose_name='Про себе')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Останній вхід')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=140, verbose_name='Дія')),
                ('entity_type', models.CharField(max_length=80, verbose_name='Сутність')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID сутності')),
                ('details_json', models.JSONField(blank=True, default=dict, verbose_name='Деталі')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=280, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='initiatives/', verbose_name='Зображення')),
                ('urgency_level', models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока'), ('emergency', 'Термінова')], default='medium', max_length=16, verbose_name='Терміновість')),
                ('format', models.CharField(choices=[('offline', 'Офлайн'), ('online', 'Онлайн'), ('hybrid', 'Гібридна')], default='offline', max_length=16, verbose_name='Формат')),
                ('city', models.CharField(max_length=100, verbose_name='Місто/регіон')),
                ('location_address', models.CharField(blank=True, max_length=220, verbose_name='Локація')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата завершення')),
                ('required_volunteers_count', models.PositiveIntegerField(default=1, verbose_name='Потрібно волонтерів')),
                ('approved_volunteers_count', models.PositiveIntegerField(default=0, verbose_name='Затверджено волонтерів')),
                ('beginner_friendly', models.BooleanField(default=True, verbose_name='Підходить новачкам')),
                ('accessibility_notes', models.TextField(blank=True, verbose_name='Доступність')),
                ('safety_notes', models.TextField(blank=True, verbose_name='Безпекові нотатки')),
                ('contact_person', models.CharField(blank=True, max_length=140, verbose_name='Контактна особа')),
                ('expected_impact', models.CharField(blank=True, max_length=220, verbose_name='Очікуваний вплив')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опублікована'), ('paused', 'Призупинена'), ('completed', 'Завершена'), ('cancelled', 'Скасована'), ('archived', 'Архівована')], default='published', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_initiatives', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiatives', to='hub.initiativecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Подана'), ('under_review', 'На розгляді'), ('approved', 'Підтверджена'), ('rejected', 'Відхилена'), ('cancelled', 'Скасована'), ('attended', 'Участь підтверджена'), ('missed', 'Не з’явився')], default='submitted', max_length=24, verbose_name='Статус')),
                ('motivation_text', models.TextField(max_length=1000, verbose_name='Мотивація')),
                ('coordinator_comment', models.TextField(blank=True, verbose_name='Коментар координатора')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина відхилення')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Причина скасування')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hub.initiative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=180, verbose_name='Тема')),
                ('status', models.CharField(choices=[('open', 'Відкрите'), ('waiting_for_volunteer', 'Очікує волонтера'), ('waiting_for_coordinator', 'Очікує координатора'), ('resolved', 'Вирішене'), ('closed', 'Закрите')], default='open', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.application')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_threads', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.initiative')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=2000, verbose_name='Повідомлення')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hub.messagethread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60, verbose_name='Тип')),
                ('title', models.CharField(max_length=180, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Опис')),
                ('logo', models.ImageField(blank=True, upload_to='organizations/', verbose_name='Логотип')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('address', models.CharField(blank=True, max_length=220, verbose_name='Адреса')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Контактний email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('status', models.CharField(choices=[('pending', 'Очікує перевірки'), ('active', 'Активна'), ('suspended', 'Призупинена')], default='active', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinators', models.ManyToManyField(blank=True, related_name='coordinated_organizations', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='hub.organization'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Підтверджені години')),
                ('certificate_number', models.CharField(max_length=64, unique=True, verbose_name='Номер сертифіката')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата видачі')),
                ('status', models.CharField(choices=[('issued', 'Видано'), ('revoked', 'Анульовано')], default='issued', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.initiative')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.organization')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Назва зміни')),
                ('shift_date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Початок')),
                ('end_time', models.TimeField(verbose_name='Завершення')),
                ('location', models.CharField(blank=True, max_length=220, verbose_name='Місце')),
                ('max_volunteers', models.PositiveIntegerField(default=5, verbose_name='Максимум волонтерів')),
                ('approved_count', models.PositiveIntegerField(default=0, verbose_name='Затверджено')),
                ('status', models.CharField(choices=[('open', 'Відкрита'), ('full', 'Заповнена'), ('closed', 'Закрита'), ('cancelled', 'Скасована')], default='open', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hub.initiative')),
            ],
            options={
                'ordering': ['shift_date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='hub.shift'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='hub.skill'),
        ),
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.BooleanField(default=True, verbose_name='Будні')),
                ('weekends', models.BooleanField(default=True, verbose_name='Вихідні')),
                ('mornings', models.BooleanField(default=False, verbose_name='Ранок')),
                ('afternoons', models.BooleanField(default=True, verbose_name='День')),
                ('evenings', models.BooleanField(default=False, verbose_name='Вечір')),
                ('remote_only', models.BooleanField(default=False, verbose_name='Тільки дистанційно')),
                ('preferred_city', models.CharField(blank=True, max_length=100, verbose_name='Бажане місто/регіон')),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.25)], verbose_name='Години')),
                ('description', models.TextField(max_length=1200, verbose_name='Опис виконаної роботи')),
                ('evidence_file', models.FileField(blank=True, upload_to='evidence/', verbose_name='Підтвердження')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('submitted', 'Подано'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='submitted', max_length=16, verbose_name='Статус')),
                ('review_comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='hub.initiative')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hours', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.shift')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.skill')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('volunteer', 'skill')},
            },
        ),
    ]
