# Generated by Django 5.2.15 on 2026-06-18 16:02

import apps.hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerhour',
            name='evidence_file',
            field=models.FileField(blank=True, storage=apps.hub.models.evidence_file_storage, upload_to='evidence/', verbose_name='Підтвердження'),
        ),
    ]
