# Generated by Django 5.2.15 on 2026-06-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_volunteerhour_evidence_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['initiative', 'status', '-created_at'], name='hub_applica_initiat_bc547e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['volunteer', 'status', '-created_at'], name='hub_applica_volunte_62ffa5_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['shift', 'status'], name='hub_applica_shift_i_650811_idx'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['status', '-created_at'], name='hub_initiat_status_57d50f_idx'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='hub_initiat_organiz_9bedfa_idx'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['city', 'status'], name='hub_initiat_city_d6bb12_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'is_read', 'created_at'], name='hub_message_thread__543363_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'sender'], name='hub_message_is_read_8e4d43_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['volunteer', '-updated_at'], name='hub_message_volunte_cef06e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['coordinator', '-updated_at'], name='hub_message_coordin_0b0a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['status', '-updated_at'], name='hub_message_status_fc873f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='hub_notific_user_id_204bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type', '-created_at'], name='hub_notific_user_id_4a174e_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['initiative', 'status', 'shift_date'], name='hub_shift_initiat_b77046_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status', 'shift_date', 'start_time'], name='hub_shift_status_be35f1_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerhour',
            index=models.Index(fields=['initiative', 'status', '-submitted_at'], name='hub_volunte_initiat_5a5845_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerhour',
            index=models.Index(fields=['volunteer', 'status', '-submitted_at'], name='hub_volunte_volunte_9890f8_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerhour',
            index=models.Index(fields=['shift', 'status'], name='hub_volunte_shift_i_99a003_idx'),
        ),
    ]
