# Generated by Django 5.2.15 on 2026-06-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_application_hub_applica_initiat_bc547e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hub.application'),
        ),
        migrations.AddField(
            model_name='notification',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hub.certificate'),
        ),
        migrations.AddField(
            model_name='notification',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hub.initiative'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hub.messagethread'),
        ),
        migrations.AddField(
            model_name='notification',
            name='volunteer_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hub.volunteerhour'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='hub.application'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='hub.initiative'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['initiative', '-created_at'], name='hub_notific_initiat_de7b13_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['application', '-created_at'], name='hub_notific_applica_b902a0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['volunteer_hour', '-created_at'], name='hub_notific_volunte_9cebf6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['message_thread', '-created_at'], name='hub_notific_message_30896b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['certificate', '-created_at'], name='hub_notific_certifi_b8db49_idx'),
        ),
    ]
